/**
 * MetricsCollector Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('MetricsCollector', () => {
  it('should be importable', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    expect(mod.MetricsCollector).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(instance).toBeTruthy();
  });

  it('should have recordMetrics method', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(typeof instance.recordMetrics).toBe('function');
  });

  it('should have getMetrics method', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(typeof instance.getMetrics).toBe('function');
  });

  it('should have getSessionMetrics method', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(typeof instance.getSessionMetrics).toBe('function');
  });

  it('should have getAggregatedMetrics method', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(typeof instance.getAggregatedMetrics).toBe('function');
  });

  it('should have writeToAnalyticsEngine method', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(typeof instance.writeToAnalyticsEngine).toBe('function');
  });

  it('should have storeLatestMetrics method', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(typeof instance.storeLatestMetrics).toBe('function');
  });

  it('should have getStoredSessionMetrics method', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(typeof instance.getStoredSessionMetrics).toBe('function');
  });

  it('should have getStoredAggregation method', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(typeof instance.getStoredAggregation).toBe('function');
  });

  it('should have storeAggregation method', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(typeof instance.storeAggregation).toBe('function');
  });

  it('should have performPeriodicAggregation method', async () => {
    const mod = await import('workers/moq-edge/metrics-collector');
    const instance = new mod.MetricsCollector();
    expect(typeof instance.performPeriodicAggregation).toBe('function');
  });
});
