/**
 * MOQSessionDurableObject Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('MOQSessionDurableObject', () => {
  it('should be importable', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    expect(mod.MOQSessionDurableObject).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(instance).toBeTruthy();
  });

  it('should have fetch method', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(typeof instance.fetch).toBe('function');
  });

  it('should have initializeSession method', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(typeof instance.initializeSession).toBe('function');
  });

  it('should have handleConnect method', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(typeof instance.handleConnect).toBe('function');
  });

  it('should have handleMessage method', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(typeof instance.handleMessage).toBe('function');
  });

  it('should have handleStatus method', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(typeof instance.handleStatus).toBe('function');
  });

  it('should have handleMetrics method', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(typeof instance.handleMetrics).toBe('function');
  });

  it('should have handleClose method', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(typeof instance.handleClose).toBe('function');
  });

  it('should have processMessage method', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(typeof instance.processMessage).toBe('function');
  });

  it('should have handleSubscribe method', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(typeof instance.handleSubscribe).toBe('function');
  });

  it('should have handleUnsubscribe method', async () => {
    const mod = await import('workers/moq-edge/moq-session-do');
    const instance = new mod.MOQSessionDurableObject();
    expect(typeof instance.handleUnsubscribe).toBe('function');
  });
});
