/**
 * TransportNegotiationService Smoke Tests
 * Auto-generated by scripts/generate-smoke-tests.py
 */

import { describe, it, expect, vi } from 'vitest';

// Mock external dependencies
vi.mock('@/lib/supabase/service-role', () => ({
  createServiceRoleClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    insert: vi.fn().mockReturnThis(),
    update: vi.fn().mockReturnThis(),
    delete: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    rpc: vi.fn().mockResolvedValue({ data: null, error: null }),
  }),
}));

vi.mock('@/lib/supabase/server', () => ({
  createClient: () => ({
    from: vi.fn().mockReturnThis(),
    select: vi.fn().mockReturnThis(),
    auth: { getUser: vi.fn().mockResolvedValue({ data: { user: null }, error: null }) },
  }),
}));

vi.mock('@sentry/nextjs', () => ({
  captureException: vi.fn(),
  withScope: vi.fn((fn) => fn({ setTag: vi.fn() })),
}));

vi.mock('@/lib/observability/kubiks', () => ({
  traceExternalAPI: vi.fn((_svc, _op, fn) => fn()),
  setSpanAttributes: vi.fn(),
}));

vi.mock('@/lib/base-service', () => ({
  BaseService: class {
    protected logger = { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
    protected traceOperation(_name: string, fn: () => Promise<unknown>) { return fn(); }
  },
}));

describe('TransportNegotiationService', () => {
  it('should be importable', async () => {
    const mod = await import('workers/moq-edge/transport-negotiation');
    expect(mod.TransportNegotiationService).toBeDefined();
  });

  it('should be instantiable', async () => {
    const mod = await import('workers/moq-edge/transport-negotiation');
    const instance = new mod.TransportNegotiationService();
    expect(instance).toBeTruthy();
  });

  it('should have negotiateTransport method', async () => {
    const mod = await import('workers/moq-edge/transport-negotiation');
    const instance = new mod.TransportNegotiationService();
    expect(typeof instance.negotiateTransport).toBe('function');
  });

  it('should have getAvailableTransports method', async () => {
    const mod = await import('workers/moq-edge/transport-negotiation');
    const instance = new mod.TransportNegotiationService();
    expect(typeof instance.getAvailableTransports).toBe('function');
  });

  it('should have storeNegotiationResult method', async () => {
    const mod = await import('workers/moq-edge/transport-negotiation');
    const instance = new mod.TransportNegotiationService();
    expect(typeof instance.storeNegotiationResult).toBe('function');
  });

  it('should have getTransportStatistics method', async () => {
    const mod = await import('workers/moq-edge/transport-negotiation');
    const instance = new mod.TransportNegotiationService();
    expect(typeof instance.getTransportStatistics).toBe('function');
  });
});
